# Generated by Django 3.1.2 on 2020-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201125_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='NoOfTime_tabSwitch',
            field=models.PositiveIntegerField(blank=True, help_text='Number of user switched tab', null=True, verbose_name='tab_switching'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='Timer',
            field=models.DateTimeField(blank=True, help_text='Timer for quiz', null=True, verbose_name='Timer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_timer',
            field=models.BooleanField(blank=True, default=False, help_text='If True, Timer will enable, If False Timer disable', verbose_name='Is_Timer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='procting',
            field=models.BooleanField(blank=True, default=False, verbose_name='Procting'),
        ),
    ]
