# Generated by Django 3.1.2 on 2020-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='From',
            field=models.TextField(blank=True, null=True),
        ),
    ]
