# Generated by Django 3.1.2 on 2020-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='acknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
