# Generated by Django 3.1.2 on 2020-11-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_acknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcement/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announcementfiles', to='announcements.announcement')),
            ],
        ),
    ]
